FROM python:3.11
WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY clean_data.py .
COPY sample_data.csv .
COPY main.py .    

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]