version: '3'
services:
  backend:
    build: ./data_backend
    ports:
      - "8000:8000"
    volumes:
      - ./data_backend/sample_data.csv:/app/sample_data.csv

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend